import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nike",
  description: "Generated by create next app",
  icons: ["https://static.nike.com.br/images/meta/favicon-32x32.png"],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
